function createfigure(yvector1)
%CREATEFIGURE(YVECTOR1)
%  YVECTOR1:  bar yvector

%  Auto-generated by MATLAB on 09-Nov-2016 22:06:16

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'YGrid','on','XGrid','on',...
    'XTickLabel',{'Food, Bev., Tob. ','Textiles ','Wood, Paper ','Petroleum, Coal ','Chemicals ','Plastics, Rubber ','Nonmetallic ','Metal ','Machinery ','Computer, Elect. ','Transport Mfg. ','Furniture Mfg. '},...
    'XTickLabelRotation',90,...
    'XTick',[1 2 3 4 5 6 7 8 9 10 11 12],...
    'GridAlpha',1,...
    'GridLineStyle',':',...
    'FontSize',12,...
    'Position',[0.2078125 0.527675276752767 0.533125 0.42218922189222]); 
% 'Position',[0.2078125 0.265645888575371 0.533125 0.684218610069616]);
%% Uncomment the following line to preserve the X-limits of the axes
 xlim(axes1,[0.5 12.5]);
%% Uncomment the following line to preserve the Y-limits of the axes
 ylim(axes1,[-20 60]);
box(axes1,'on');
hold(axes1,'on');

% Create bar
bar(yvector1,'FaceColor',[0 0.498039215686275 0],'BarWidth',0.4);

% Create ylabel
ylabel('Percentage change (%)','FontSize',12);

