function createfigure(YMatrix1, YMatrix2, YMatrix3, YMatrix4)
%CREATEFIGURE(YMATRIX1, YMATRIX2, YMATRIX3, YMATRIX4)
%  YMATRIX1:  matrix of y data
%  YMATRIX2:  matrix of y data
%  YMATRIX3:  matrix of y data
%  YMATRIX4:  matrix of y data

%  Auto-generated by MATLAB on 09-Nov-2016 21:57:25

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'YGrid','on','XGrid','on',...
    'XTickLabel',{'2000','2003:Q4','2006:Q4','2009:Q4','2012:Q4'},...
    'XTick',[2 13 25 37 49],...
    'FontSize',12,...
    'Position',[0.570340909090909 0.583837209302326 0.334659090909091 0.341162790697675]);
%% Uncomment the following line to preserve the X-limits of the axes
 xlim(axes1,[2 55]);
%% Uncomment the following line to preserve the Y-limits of the axes
%  ylim(axes1,[60.5 63]);
box(axes1,'on');
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(YMatrix1,'Parent',axes1,'LineWidth',3);
set(plot1(1),'DisplayName','Services ',...
    'LineStyle','-.',...
    'Color',[0.850980401039124 0.325490206480026 0.0980392172932625]);

% Create xlabel
xlabel('Time (quarters)','FontSize',12);

% Create ylabel
ylabel('Employment effects (%)','FontSize',12);

% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','southeast','FontSize',8,...
    'EdgeColor',[0.15 0.15 0.15]);

% Create axes
axes2 = axes('Parent',figure1,'YGrid','on','XGrid','on',...
    'XTickLabel',{'2000','2003:Q4','2006:Q4','2009:Q4','2012:Q4'},...
    'XTick',[2 13 25 37 49],...
    'FontSize',12,...
    'Position',[0.570340909090909 0.11 0.334659090909091 0.341162790697674]);
%% Uncomment the following line to preserve the X-limits of the axes
 xlim(axes2,[2 55]);
%% Uncomment the following line to preserve the Y-limits of the axes
%  ylim(axes2,[7.5 7.75]);
box(axes2,'on');
hold(axes2,'on');

% Create multiple lines using matrix input to plot
plot2 = plot(YMatrix2,'Parent',axes2,'LineWidth',3);
set(plot2(1),'DisplayName','Construction',...
    'LineStyle','-.',...
    'Color',[0.850980401039124 0.325490206480026 0.0980392172932625]);
% Create xlabel
xlabel('Time (quarters)','FontSize',12);

% Create ylabel
ylabel('Employment effects (%)','FontSize',12);

% Create legend
legend2 = legend(axes2,'show');
set(legend2,'Location','southeast','FontSize',8,...
    'EdgeColor',[0.15 0.15 0.15]);

% Create axes
axes3 = axes('Parent',figure1,'YGrid','on','XGrid','on',...
    'XTickLabel',{'2000','2003:Q4','2006:Q4','2009:Q4','2012:Q4'},...
    'XTick',[2 13 25 37 49],...
    'FontSize',12,...
    'Position',[0.13 0.11 0.334659090909091 0.341162790697674]);
%% Uncomment the following line to preserve the X-limits of the axes
 xlim(axes3,[2 55]);
%% Uncomment the following line to preserve the Y-limits of the axes
%  ylim(axes3,[14.8 15]);
box(axes3,'on');
hold(axes3,'on');

% Create multiple lines using matrix input to plot
plot3 = plot(YMatrix3,'Parent',axes3,'LineWidth',3);
set(plot3(1),'DisplayName','W & Retail ',...
    'LineStyle','-.',...
    'Color',[0.850980401039124 0.325490206480026 0.0980392172932625]);

% Create xlabel
xlabel('Time (quarters)','FontSize',12);

% Create ylabel
ylabel('Employment effects (%)','FontSize',12);

% Create legend
legend3 = legend(axes3,'show');
set(legend3,'Location','southeast','FontSize',8,...
    'EdgeColor',[0.15 0.15 0.15]);

% Create axes
axes4 = axes('Parent',figure1,'YGrid','on','XGrid','on',...
    'XTickLabel',{'2000','2003:Q4','2006:Q4','2009:Q4','2012:Q4'},...
    'XTick',[2 13 25 37 49],...
    'FontSize',12,...
    'Position',[0.13 0.583837209302326 0.334659090909091 0.341162790697675]);
%% Uncomment the following line to preserve the X-limits of the axes
 xlim(axes4,[2 55]);
%% Uncomment the following line to preserve the Y-limits of the axes
  ylim(axes4,[-0.6 0]);
box(axes4,'on');
hold(axes4,'on');

% Create multiple lines using matrix input to plot
plot4 = plot(YMatrix4,'Parent',axes4,'LineWidth',3);
set(plot4(1),'DisplayName','Manufacturing ',...
   'LineStyle','-.',...
    'Color',[0.850980401039124 0.325490206480026 0.0980392172932625]);
% Create xlabel
xlabel('Time (quarters)','FontSize',12);

% Create ylabel
ylabel('Employment effects (%)','FontSize',12);

% Create legend
legend4 = legend(axes4,'show');
set(legend4,'FontSize',8,'EdgeColor',[0.15 0.15 0.15]);

